[package]
name = "deepeedeekay"
version = "0.1.0"
edition = "2024"

[dependencies]
bstr = "1.12.0"
bytes = "1.10.1"
dpdk-sys = { version = "0.1.0", path = "sys" }
itertools = "0.14.0"
num = "0.4.3"

[workspace]
members = ["sys"]

[dev-dependencies]
static_assertions = "1.1.0"

